language: ruby
rvm:
  - 2.5.3
services:
  - postgresql
addons:
  chrome: stable
before_install:
  - gem i bundler -v 2.0.2
script:
  - gem --version
  - bundle version
  - bundle install --jobs=3 --retry=3 --deployment
  - yarn install
  - bundle exec rake db:setup
  - bundle exec rake db:test:prepare
  - bundle exec rubocop
  - bundle exec rspec